export { default as nft1 } from "./nft1.png"
export { default as nft2 } from "./nft2.png"
export { default as nft3 } from "./nft3.png"
export { default as nft4 } from "./nft4.png"
export { default as nft5 } from "./nft5.png"