export { default as h1 } from "./h1.png"
export { default as h2 } from "./h2.png"
export { default as h3 } from "./h3.png"
export { default as h4 } from "./h4.png"
export { default as h5 } from "./h5.png"